version: '1'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://fastadmin:fast#123@db:5432/fastapi
  
  db:
    image: postgres:15-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastadmin
      - POSTGRES_PASSWORD=fast#123
      - POSTGRES_DB=fastapi

volumes:
  postgres_data: